### ISSUE TITLE
在Windows10上，用CMake编译，报错：Architecture not supported，如下图所示，是否暂不支持Windows平台啊？

### ISSUE THREAD

**Issue by retioa11** [CVCUDA/CV-CUDA#105]
![image](https://github.com/CVCUDA/CV-CUDA/assets/81463532/80933239-9c0c-4ad1-aeb5-a6bfbd631585)

**Comment by jay19453** [comment]
你好 现在你在windows上面解决此问题了吗 我现在也想要在windows平台进行编译

**Comment by retioa11** [comment]
> 
没有呢，感觉是暂不支持Windows吧。

**Comment by zgjja** [comment]
代码不支持win平台的

**Comment by shiremathNV** [comment]
Hello @retioa11 - Thanks for contacting us with your question. 

We unfortunately do not support Windows OS at this point as a majority of our initial developers had expressed Linux support being important for them. We are however looking into adding native Windows support in a future release of CV-CUDA. 

In order to help prioritize this request, could you share any details on your use case for Win OS support? 

We are tracking the Windows support internally on our roadmap. Closing this request for now, please feel free to provide more details and re-open this ticket if you have a follow-up question.
