### ISSUE TITLE
[BUG] import nvcv cvcuda 失败

### ISSUE THREAD

**Issue by tigerzjh** [CVCUDA/CV-CUDA#24]
**Describe the bug**
使用tar 方式安装，由于权限原因无法使用deb方式。对应的路径如下：
![image](https://user-images.githubusercontent.com/23514705/211742154-94498ca3-668d-42dd-9997-d437636c9502.png)
我是将这个路径下的so，放入环境变量吗？
export PYTHONPATH=/home/zhangjianhu/softwars/opt/nvidia/cvcuda0/lib/x86_64-linux-gnu:$PYTHONPATH
之后仍然import失败

**Comment by bhaefnerNV** [comment]
Hi @tigerzjh,
Thank you for your interest in CVCUDA.
Could you provide more details on the system you're using, eg via the output of the [print_env.sh script](https://github.com/CVCUDA/CV-CUDA/blob/main/print_env.sh)?

Since [release 0.6.0-beta](https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.6.0-beta), we provide standalone python wheels, including tooling and documentation to generate them for python versions 3.8, 3.9, 3.10, and 3.11. The python wheels can be found under the same link above. If you'd to build your own python wheels, this can automatically be triggered, when building CVCUDA in release mode, please see [here ](https://github.com/CVCUDA/CV-CUDA#build-from-source) for further details.

**Comment by bhaefnerNV** [comment]
Hi @tigerzjh ,
We will close this issue for now, due to inactivity - if the problem persists, please feel free to reopen along with some information on your system, ie the output when running the [prinv_env.sh](https://github.com/CVCUDA/CV-CUDA/blob/main/print_env.sh) script.
